4.8.16 dev
KB-iGOT/sunbird-lms-service pull request #4
Opened 2024-08-07 06:17 UTC by karthik-tarento

2024-08-07 06:37 UTC, Sahil-tarento requested changes

2024-08-07 06:37 UTC, Sahil-tarento commented on service/src/main/java/org/sunbird/service/user/UserProfileReadService.java
> +        if (!list.isEmpty() && list.get(0) instanceof HashMap) {
Please handle null pointer and try to use collectionUtils as it handle the proper null pointer

2024-08-07 06:37 UTC, Sahil-tarento commented on service/src/main/java/org/sunbird/actor/user/UserUpdateActor.java
> +      }catch (Exception e){
please do formatting

2024-08-07 06:37 UTC, Sahil-tarento commented on service/src/main/java/org/sunbird/actor/user/UserUpdateActor.java
> +        logger.info("error while generating mentorship event");
The error should give proper msg and it should be error

2024-08-07 06:37 UTC, Sahil-tarento commented on service/src/main/java/org/sunbird/service/user/UserProfileReadService.java
> +        } else if (!list.isEmpty() && list.get(0) instanceof String) {
Please handle null pointer and try to use collectionUtils as it handle the proper null pointer

2024-08-07 06:37 UTC, Sahil-tarento commented on service/src/main/java/org/sunbird/service/user/impl/UserServiceImpl.java
> +        ((List<Map<String, Object>>) cassandraResponse.getResult().get(JsonKey.RESPONSE)).stream()
Plead do formatting

2024-08-07 06:37 UTC, Sahil-tarento commented on service/src/main/java/org/sunbird/service/user/impl/UserServiceImpl.java
> +        ((List<Map<String, Object>>) response.getResult().get(JsonKey.RESPONSE)).stream()
Why you do typecast of not assign to any variable

2025-03-12 13:20 UTC, closed without merging

2025-03-12 13:20 UTC, karthik-tarento commented
this is not required